#TYPES MODEL
type User {
  id: String!
  encrypted_id: String!
  name: String!
  email: String!
  role: String!
  designation: String
  created_at: String!
  updated_at: String!
}

type Officials {
  id: String!
  encrypted_id: String!
  name: String!
  address: String!
  position: String!
  status: String!
  photo: String!
  created_at: String!
  updated_at: String!
  user: User @hasOne
  
}

type Categories {
  id: String!
  encrypted_id: String!
  category: String!
  parentID: String!
  created_at: String!
  totalFiles: Int! @count(relation: "totalFiles")
}

type Files {
  id: ID!
  encrypted_id: String!
  categoryID: String
  municipalStatus: String
  provincialStatus: String
  authorID: String
  firstReadingDate: String
  publicHearingDate: String
  secondReadingDate: String
  thirdReadingDate: String
  ordinanceNumber: String
  finalOrdinanceNumber: String
  title: String
  finalTitle: String
  enactmentDate: String
  lceapprovalDate: String
  transmittalDate: String
  spslapprovalDate: String
  postStatus: String
  publishStatus: String
  implementationDate: String
  file: String
  created_at: String
  updated_at: String
  category: Categories @hasOne
  coAuthors: [CoAuthor]
  author: Officials @hasOne
}

type CoAuthor {
  id: ID!
  encrypted_id: String!
  fileID: String
  officialID: String
  official: Officials @hasOne
}

type BrgyFiles {
  id: ID!
  encrypted_id: String!
  title: String
  barangayID: String
  dateReceived: String
  status: String
  file: String
  appropriation: String
  barangay: Barangay @hasOne
}

type Barangay {
  id: ID!
  encrypted_id: String!
  brgyname: String
  brgyfiles: [BrgyFiles]
}



# TYPES CONTAINERS FOR PAGES

type Welcome {
  filesListPaginated: FilePagination!
}

type Dashboard {
  adminsCount: Int
  officialsCount: Int
  categoriesCount: Int
  filesCount: Int
  files: [Files]
}

type Category {
  categoriesList: [Categories!]!
}

type File {
  categoryName: Categories!
  filesListPaginated: FilePagination!
  authors: [Officials!]!
  subCategoriesList: [Categories!]!
}

type FilePagination {
  data: [Files!]!
  paginatorInfo: PaginatorInfo!
}

type PaginatorInfo {
  currentPage: Int!
  lastPage: Int!
  perPage: Int!
  total: Int!
  hasMorePages: Boolean!
}

type ViewFile {
  file: Files
}

type BrgyOrdinances {
  brgyordinancesList: [Barangay]
}

type ViewBrgy {
  brgyName: Barangay!
  filesListPaginated: BrgyFilePagination!
}

type BrgyFilePagination {
  data: [BrgyFiles!]!
  paginatorInfo: PaginatorInfo!
}

#GUEST QUERY - WELCOME PAGE
extend type Query {
  welcome(page: Int, first: Int!, search: String): Welcome
    @field(resolver: "App\\GraphQL\\Queries\\Guest\\Welcome")
}

# ADMIN QUERY - PAGES
type Query @guard {
  dashboard: Dashboard 
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\Dashboard")

  admins: [User!]!
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\AdminManagement")

  officials: [Officials!]!
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\ElectedOfficials")
  
  categories: Category
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\FileManager")

  files(id: String!, page: Int, first: Int!, search: String): File
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\File")

  viewFile(id: String!): ViewFile
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\ViewFile")

  brgyordinances: BrgyOrdinances
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\BrgyOrdinances")

  brgyfiles(id: String!, page: Int, first: Int!, search: String): ViewBrgy
    @field(resolver: "App\\GraphQL\\Queries\\Admin\\BrgyFile")
}

#USER QUERY - PAGES
extend type Query @guard {
  userdashboard: Dashboard 
    @field(resolver: "App\\GraphQL\\Queries\\User\\Dashboard")

  userofficials: [Officials!]!
    @field(resolver: "App\\GraphQL\\Queries\\User\\ElectedOfficials")
  
  usercategories: Category
    @field(resolver: "App\\GraphQL\\Queries\\User\\FileManager")

  userfiles(id: String!, page: Int, first: Int!, search: String): File
    @field(resolver: "App\\GraphQL\\Queries\\User\\File")

  userviewFile(id: String!): ViewFile
    @field(resolver: "App\\GraphQL\\Queries\\User\\ViewFile")
}
